# -*- coding: utf-8 -*-

from . import account_move_line
from . import account_move_send
from . import account_move
from . import calendar_event
from . import crm_lead
from . import header_footer
from . import helpdesk_ticket
from . import ir_ui_view
from . import mail_compose_message
from . import mail_thread
from . import mail_wizard_invite
from . import proquotes_variant
from . import preconfigured_section
from . import preconfigured_section_line
from . import product_product
from . import product_template
from . import project_task
from . import purchase_order
from . import renewal_map
from . import renewal_entry
from . import res_company
from . import res_partner
from . import res_users
from . import res_users_company_footer
from . import sale_order_line
from . import sale_order_template_line
from . import sale_order_template
from . import sale_order
from . import stock_lot
from . import stock_picking
from . import res_config_settings
from . import ccp_period_config
from . import ccp_scanner_config
from . import ccp_type_config
from . import rental_order_wizard
from . import rental_order_wizard_line
from . import models
