# -*- coding: utf-8 -*-
{
    "name": "ProQuotes",
    "summary": """Module that adds features to Quotes, Invoices, Purchases, and Deliveries.""",
    "description": """This module adds renewal quote features, multiple choice/selection options for clients, a variety of new fields, and better user interface.""",
    "author": "Ezekiel deBlois",
    "license": "LGPL-3",
    "category": "Sales",
    "depends": [
        "sale_stock",
        "base",
        "web",
        "mail",
        "mail_group",
        "account",
        "proportal",
        "stock",
        "website",
        "sale_management",
        "sale",
        "hr",
        "digest",
        "portal",
        "contacts",
        "stock_account",
        "project",
        "sale_project",
        "website_sale",
        "sale_timesheet",
        "purchase",
        "crm",
        "website_crm",
    ],
    "assets": {
        "web.assets_common": [
            "proquotes/static/src/CSS/foldProducts.css",
            "proquotes/static/src/CSS/pdf.css",
            "proquotes/static/src/CSS/user-info.css",
            "proquotes/static/src/CSS/quoteStyle.css",
            "proquotes/static/src/CSS/quoteHeaderText.css",
            "proquotes/static/src/CSS/rental_fold.css",
            "proquotes/static/src/CSS/backend.css",
            "proquotes/static/src/JS/fold.js",
            "proquotes/static/src/JS/poNumber.js",
            "proquotes/static/src/JS/rental.js",
            "proquotes/static/src/JS/website_preview.js",
        ],
        'web.assets_frontend': [
            "proquotes/static/src/CSS/header.css",
            "proquotes/static/src/CSS/store.css",
            "proquotes/static/src/JS/price.js",
            "proquotes/static/src/JS/fold.js",
            "proquotes/static/src/JS/poNumber.js",
            "proquotes/static/src/JS/rental.js",
            "proquotes/static/src/JS/website_preview.js",
            ('replace', 'portal/static/src/signature_form/signature_form.js',
             'proquotes/static/src/JS/signature_form.js'),
        ],
        'web.assets_backend': [
            "proquotes/static/src/JS/website_preview.js",
        ],
        'website.assets_wysiwyg': [
            'proquotes/static/src/JS/rental_quote_form_editor.js',
        ],
    },

    "version": "17.0",

    # always loaded
    "data": [
        "security/ir.model.access.csv",
        # quotes
        "views/Quote/quote_report.xml",
        "views/Quote/quote_preview.xml",
        "views/Quote/quote_internal.xml",
        "views/Quote/quote_template.xml",
        "views/Quote/quote_wizard.xml",
        # invoices
        "views/Invoice/invoice_report.xml",
        "views/Invoice/invoice_preview.xml",
        "views/Invoice/invoice_internal.xml",
        "views/Invoice/follow_up_email.xml",
        # purchase
        "views/Purchase/purchase_report.xml",
        "views/Purchase/purchase_preview.xml",
        "views/Purchase/purchase_internal.xml",
        # other
        "views/Other/mail_templates.xml",
        "views/Other/stock_lot.xml",
        "views/Other/tax.xml",
        "views/Other/rentalTerms.xml",
        "views/Other/normalTerms.xml",
        "views/Other/website_logo.xml",
        "views/Other/renewalText.xml",
        "views/Quote/quoteRentalAddress.xml",
        "views/Other/mail.xml",
        "views/Other/delivery_report.xml",
        "views/Other/project_task.xml",
        "views/Other/pdf_boxed.xml",
        "views/Other/section_name.xml",
        "views/Other/internal_company_backend.xml",
        "views/Other/internal_user_backend.xml",
        "views/Other/renewal.xml",
        "views/Other/header_footer.xml",
        "views/Invoice/invoice_lot.xml",
        "views/Other/stock_picking.xml",
        "views/Other/quoteEmailFooter.xml",
        "views/Other/helpdeskTicket.xml",
        "views/Other/header_footer_values.xml",
        "views/Other/preconfigured_sections.xml",
        "views/Other/res_config_extend_view.xml",
        "views/Quote/table_align.xml",
        "views/Other/crm_lead.xml",
        "data/thanks_for_payment.xml",
    ],
}