import logging
import re
from datetime import datetime, date, timedelta
_logger = logging.getLogger(__name__)

# normalization functions and report related functions
class utilities:
    
    # -- ODOO FIELD TYPES --
    # 
    # SUPPORTED BY SYNC:
    # 
    #   char, text, html
    #   integer, float, boolean
    #   date, datetime
    #   monetary
    #   binary (images, files, signatures)
    # 
    # UNSUPPORTED BY SYNC:
    # 
    #   selection
    #   many2one, many2many, one2many

    # utility function
    # in odoo, dates are in this format: 2024-01-01
    # in sheets, dates are in this format: 2024-1-1
    # this function normalizes those values
    # also handles dates being blank or "FALSE"
    def normalize_dates(self, value):
        try:
            
            # handle none or false values
            if not value or (isinstance(value, str) and value.strip().upper() == "FALSE"):
                return ""

            # convert datetime object to string
            if isinstance(value, (datetime, date)):
                return value.strftime("%Y-%m-%d")

            # normalize string date values
            if isinstance(value, str):
                return datetime.strptime(value.strip(), "%Y-%m-%d").strftime("%Y-%m-%d")

            # fallback
            _logger.warning("normalize_date: Unexpected type for value '%s'. Returning as-is.", value)
            return str(value)

        except ValueError:
            _logger.warning("normalize_date: Invalid date value '%s'. Returning as-is.", value)
            return str(value)

    # utility function
    # in odoo, booleans are "True" or "False"
    # in sheets, booleans are "TRUE" or "FALSE" or "#REF!" if generated by a broken formula
    # this function normalizes those values
    def normalize_bools(value, field=None):

        if isinstance(value, str):
            normalized_value = value.strip().upper()

            if normalized_value in ["TRUE", "1"]:
                return True
            elif normalized_value in ["FALSE", "0", "", "#REF!"]:
                return False

            if field and field in ["publish", "expire"]:
                return normalized_value
        
        return value


    # this is a new and improved sync report function that i will move other files to using, which uses a nice xml template and formats the errors nicely.
    
    # report_content: dict of all errors to send
    # sync_type: the sync type to be printed in the header, like CCP or pricelist
    
    @staticmethod
    def send_report(report_content, sync_type, database):
        try:
            formatted_content = "\n".join(report_content)
            mail_values = {
                "subject": f"Sync Report for type: {sync_type}",
                "body_html": f"<pre>{formatted_content}</pre>",
                "email_to": "sync@store.r-e-a-l.it",
            }
            mail = database.env["mail.mail"].create(mail_values)
            mail.send()
            _logger.info("send_report: Sync report successfully sent to sync@store.r-e-a-l.it.")
        except Exception as e:
            _logger.error("send_report: Failed to send sync report email: %s", str(e), exc_info=True)
    
    @staticmethod
    def check_id(id):
        if (" " in id):
            _logger.info("ID: " + str(id))
            return False
        else:
            return True

    @staticmethod
    def check_price(price):
        if (price in ("", " ")):
            return True
        try:
            float(price)
            return True
        except Exception as e:
            _logger.info(e)
            return False

    @staticmethod
    def check_date(date) -> bool:
        """
        Validates a date string to ensure it matches the expected format.
        Logs detailed reasons if the date is invalid.

        Args:
            date (str): The date string to validate.

        Returns:
            bool: True if the date is valid, False otherwise.
        """
        if str(date) == "FALSE":
            return True  # "FALSE" is treated as valid by design

        # Check if the date matches the expected format (YYYY-MM-DD)
        date_pattern = r'^\d{4}-\d{1,2}-\d{1,2}$'
        if not re.match(date_pattern, str(date)):
            _logger.error(f"check_date: Date '{date}' does not match the format YYYY-MM-DD.")
            return False

        # Split the date into year, month, day
        try:
            year, month, day = map(int, date.split('-'))
        except ValueError:
            _logger.error(f"check_date: Date '{date}' cannot be split into year, month, and day.")
            return False

        # Check year range
        if year < 1900 or year > 2100:
            _logger.error(f"check_date: Year '{year}' in date '{date}' is out of range (1900-2100).")
            return False

        # Check month range
        if month < 1 or month > 12:
            _logger.error(f"check_date: Month '{month}' in date '{date}' is out of range (1-12).")
            return False

        # Check day range for the given month
        days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
        if (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:
            days_in_month[1] = 29  # Adjust for leap years

        if day < 1 or day > days_in_month[month - 1]:
            _logger.error(f"check_date: Day '{day}' in date '{date}' is out of range for month '{month}'.")
            return False

        return True
    # @staticmethod
    # def check_date(date) -> bool:
    #     if str(date).strip().upper() == "FALSE":
    #         return True
    #     try:
    #         # Attempt to parse the date into YYYY-MM-DD format
    #         datetime.strptime(date.strip(), "%Y-%m-%d")
    #         return True
    #     except ValueError:
    #         return False

    @staticmethod
    def buildMSG(msg: str, sheetName: str, key: str, problem: str):
        msg = msg + "<p>ERROR -> " + "Sheet: " + str(sheetName) + \
            " | Item: " + str(key) + " | " + str(problem) + "</p>\n"
        return msg

    
    ##################################################
    # Check the header of a sheet to import data
    # Input
    #   pHeaderDict: a dictionary that hold the name of the google sheet row, and
    #                the name in the internal dictionnary
    #   p_sheet: the array of the GS sheet
    #   p_sheetName: the name of the sheet
    @staticmethod
    def checkSheetHeader(p_HeaderDict, p_sheet, p_sheetName):
        o_columns = dict()
        o_msg = ""
        o_columnsMissing = False        

        for row in p_HeaderDict:
            if row in p_sheet[0]:
                o_columns[p_HeaderDict[row]] = p_sheet[0].index(row)
            else:
                o_msg = utilities.buildMSG(o_msg, p_sheetName, "Header", str(row) + " Missing")
                o_columnsMissing = True

        return o_columns, o_msg, o_columnsMissing
